### PR TITLE
Fixed Readme.md Grammer Mistakes

### PR DESCRIPTION
**Pull request by yashrajjain726**

### CODE REVIEW

**Comment by ckcr4lyf** [comment]
This is not relevant, a lot of the fixes are actually grammatically wrong given the context (bullet points), seems like a grab at adding yourself to contributors for no real contribution on the technical side?

**Comment by raivivek** [comment]
@ckcr4lyf And wanting to contribute would be a problem why? After all, the project _is_ open source. I'd say the fixes are more helpful than your comment.

**Comment by ckcr4lyf** [comment]
But not when they aren't actually fixes?

**Comment by yashrajjain726** [comment]
Please close the PR, because there were some typo mistakes which I fixed.

**Comment by ckcr4lyf** [comment]
The grammar is still incorrect, and this MR provides no value.

**Pull request closed without merging**
